import "./globals.css";

import { Geist, Geist_Mono } from "next/font/google";

import { AuthProvider } from "./context/AuthContext";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <Toaster
            position="top-center"
            reverseOrder={false}
            toastOptions={{
              // Add a custom style or change the duration
              duration: 3000, // Duration for each toast
              style: {
                background: "#333",
                color: "white",
                borderRadius: "8px",
              },
            }}
          />

          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
